### PR TITLE
Commiting test2 to BRanchX

### PR DESCRIPTION
**Pull request by vivek-anbu**
hi have commited test2 please review and approve.

### CODE REVIEW

**Comment by ar-vivek96** [comment]
hi x your code looks good please one more check

**Comment by ar-vivek96** [comment]
hi X
i have added additional test please aprove

**Comment by vivek-anbu** [comment]
hi X
i have added additional test please aprove

**Comment by ar-vivek96** [comment]
hi x your code is looks good please go ahead with merge to master branch

**Pull request merged**
